"""initial db layout

Revision ID: e7e81ce21ac0
Revises: 
Create Date: 2023-05-03 15:54:04.835295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7e81ce21ac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='filestore'
    )
    op.create_table('storages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('community_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='filestore'
    )
    op.create_table('file_containers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('file_category_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('storage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_category_id'], ['file_categories.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='filestore'
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('file_container_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_container_id'], ['file_containers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='filestore'
    )
    op.create_table('file_attributes',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value', sa.VARCHAR(length=512), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'key'),
    schema='filestore'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_attributes', schema='filestore')
    op.drop_table('files', schema='filestore')
    op.drop_table('file_containers', schema='filestore')
    op.drop_table('storages', schema='filestore')
    op.drop_table('file_categories', schema='filestore')
    # ### end Alembic commands ###
